### PR TITLE
New version with element returned

### PR DESCRIPTION
**Pull request by sgenov**
When using the plugin and initializing it with a class name, we are not able to reference the input in the callback.
I added the inputElement variable in the callback, so the user can manipulate it, based on the entered information.
I changed the version to 1.5 and updated the Plunker with the new demo version.

### CODE REVIEW

**Comment by sgenov** [comment]
I needed the functionality to validate the information entered. For an example February does not have 30 days and at position 7 in the format YYYYMMDD we should not be able to enter 3 if position 5 and 6 are 02 (February).
This required a new callback to be added, which checks if the input is correct and returns to the previous state if it is not.
I also did some changes to the bind events, since there is an issue with latest androids and especially Chrome for Android.

**Comment by sgenov** [comment]
Last change - removed a console.log

**Comment by shaungrady** [comment]
@sgenov I'm not maintaining this project anymore. Would you like to be made a collaborator?

**Comment by sgenov** [comment]
@shaungrady Yes, I can pick up the torch :) It shouldn't be a problem. Thanks for the invite :)

**Pull request merged**
